// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqffY_u4gtfKAd2FbofGOtqiGeT7JZQM',
    appId: '1:242603092871:web:7c834b17a63b84099ec122',
    messagingSenderId: '242603092871',
    projectId: 'food-delivery-app-f6241',
    authDomain: 'food-delivery-app-f6241.firebaseapp.com',
    storageBucket: 'food-delivery-app-f6241.appspot.com',
    measurementId: 'G-KP000FHVYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFp8PTt-t_kZyJ3-MKbbJIE5I0rCio-8',
    appId: '1:242603092871:android:67c83fbd083c09409ec122',
    messagingSenderId: '242603092871',
    projectId: 'food-delivery-app-f6241',
    storageBucket: 'food-delivery-app-f6241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-mDYiF61zNinuasmOZIutsC4RBcHyBYc',
    appId: '1:242603092871:ios:e1a82fbc1a3cf85e9ec122',
    messagingSenderId: '242603092871',
    projectId: 'food-delivery-app-f6241',
    storageBucket: 'food-delivery-app-f6241.appspot.com',
    androidClientId:
        '242603092871-pgj7ji5m1ujlggrltcrjh1q00umfk5c2.apps.googleusercontent.com',
    iosClientId:
        '242603092871-g4ilrdvqsc9u4uh2mdksttlnj03ik67o.apps.googleusercontent.com',
    iosBundleId: 'com.example.temple',
  );
}
